CREATE TABLE [dbo].[ACCOUNTTYPE] (
    [AT_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [AT_NAME] VARCHAR (25) NOT NULL,
    PRIMARY KEY CLUSTERED ([AT_ID] ASC),
    UNIQUE NONCLUSTERED ([AT_NAME] ASC)
);

