CREATE TABLE [dbo].[INSTALLEDPROGRAMS] (
    [IP_ID]      INT IDENTITY (1, 1) NOT NULL,
    [IP_PROGRAM] INT NULL,
    [IP_ITEM]    INT NULL,
    PRIMARY KEY CLUSTERED ([IP_ID] ASC),
    FOREIGN KEY ([IP_ITEM]) REFERENCES [dbo].[ITEMS] ([I_ID]),
    FOREIGN KEY ([IP_PROGRAM]) REFERENCES [dbo].[PROGRAMS] ([P_ID])
);

