CREATE TABLE [dbo].[ITEMSTATE] (
    [IS_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [IS_NAME] VARCHAR (25) NOT NULL,
    PRIMARY KEY CLUSTERED ([IS_ID] ASC),
    UNIQUE NONCLUSTERED ([IS_NAME] ASC)
);

