CREATE TABLE [dbo].[ITEMS] (
    [I_ID]    INT          IDENTITY (1, 1) NOT NULL,
    [I_NAME]  VARCHAR (50) NULL,
    [I_TYPE]  INT          NULL,
    [I_STATE] INT          NULL,
    PRIMARY KEY CLUSTERED ([I_ID] ASC),
    FOREIGN KEY ([I_STATE]) REFERENCES [dbo].[ITEMSTATE] ([IS_ID]),
    FOREIGN KEY ([I_TYPE]) REFERENCES [dbo].[ITEMTYPE] ([IT_ID])
);

