CREATE TABLE [dbo].[ITEMTYPE] (
    [IT_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [IT_NAME] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([IT_ID] ASC),
    UNIQUE NONCLUSTERED ([IT_NAME] ASC)
);

