CREATE TABLE [dbo].[PROGRAMS] (
    [P_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [P_NAME] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([P_ID] ASC),
    UNIQUE NONCLUSTERED ([P_NAME] ASC)
);

