CREATE TABLE [dbo].[RESERVATION] (
    [R_ID]   INT IDENTITY (1, 1) NOT NULL,
    [R_USER] INT NULL,
    PRIMARY KEY CLUSTERED ([R_ID] ASC),
    FOREIGN KEY ([R_USER]) REFERENCES [dbo].[USERS] ([U_ID])
);

