CREATE TABLE [dbo].[USERS] (
    [U_ID]          INT          IDENTITY (1, 1) NOT NULL,
    [U_FIRST_NAME]  VARCHAR (20) NULL,
    [U_LAST_NAME]   VARCHAR (20) NULL,
    [U_EMAIL]       VARCHAR (50) NOT NULL,
    [U_USERNAME]    VARCHAR (50) NOT NULL,
    [U_PASSWORD]    VARCHAR (50) NOT NULL,
    [U_ACCOUNTTYPE] INT          NULL,
    PRIMARY KEY CLUSTERED ([U_ID] ASC),
    FOREIGN KEY ([U_ACCOUNTTYPE]) REFERENCES [dbo].[ACCOUNTTYPE] ([AT_ID]),
    UNIQUE NONCLUSTERED ([U_EMAIL] ASC),
    UNIQUE NONCLUSTERED ([U_USERNAME] ASC)
);

